services:
    db:
        image: postgres:16
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            POSTGRES_DB: "mydatabase"
            POSTGRES_USER: "myuser"
            POSTGRES_PASSWORD: "mypassword"
        networks:
            - result-tier
            - back-tier
        restart: always

    redis:
        image: redis:7
        expose:
            - "6379"
        networks:
            - poll-tier
            - back-tier
        restart: always
    
    poll:
        build: ./poll
        ports:
            - "5000:80"
        environment:
            REDIS_HOST: "redis"
        networks:
            - poll-tier
        depends_on:
            -redis
        restart: always

    worker:
        build: ./worker
        environment:
            REDIS_HOST: "redis"
            POSTGRES_HOST: "db"
            POSTGRES_PORT: "5432"
            POSTGRES_DB: "mydatabase"
            POSTGRES_USER: "myuser"
            POSTGRES_PASSWORD: "mypassword"
        networks:
            - back-tier
        depends_on:
            -db
            -redis
        restart: always

    result:
        build: ./result
        ports:
            - "5001:80"
        environment:
            POSTGRES_HOST: "db"
            POSTGRES_PORT: "5432"
            POSTGRES_DB: "mydatabase"
            POSTGRES_USER: "myuser"
            POSTGRES_PASSWORD: "mypassword"
        networks:
            - result-tier
        depends_on:
            -db
        restart: always

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data:
        driver: local