env:
  environment: LunarLander-v3
  render_mode: rgb_array

algo:
  type: dqn

hypers:
  BATCH_SIZE: 128
  GAMMA: 0.99
  EPS_START: 1.0
  EPS_END: 0.01
  EPS_DECAY: 2500
  TAU: 0.005
  LR: 0.0003

parameters:
  ENABLE_WIND: false
  WIND_POWER: 0.0
  TURBULENCE_POWER: 0
  GRAVITY: -6

seed:
  number: [42]