##
## EPITECH PROJECT, 2026
## Makefile
## File description:
## Makefile
##

all:
	$(MAKE) -C ./client all
	$(MAKE) -C ./server all

clean:
	$(MAKE) -C ./client clean
	$(MAKE) -C ./server clean

fclean:		clean
	$(MAKE) -C ./client fclean
	$(MAKE) -C ./server fclean

re:		fclean all
